### ISSUE TITLE
RuntimeError Problem

### ISSUE THREAD

**Issue by congwei45** [ywyue/AGILE3D#10]
I encountered the following problems, do you know how to fix it?
Start training
Traceback (most recent call last):
  File "/data/cw/Experiment/AGILE3D/main.py", line 261, in <module>
    main(args)
  File "/data/cw/Experiment/AGILE3D/main.py", line 189, in main
    train_stats, train_total_iter = train_one_epoch(
  File "/data/cw/Experiment/AGILE3D/engine.py", line 53, in train_one_epoch
    pcd_features, aux, coordinates, pos_encodings_pcd = model.forward_backbone(data, raw_coordinates=raw_coords)
  File "/data/cw/Experiment/AGILE3D/models/agile3d.py", line 173, in forward_backbone
    coords.append(self.pooling(coords[-1]))
  File "/home/cw/anaconda3/envs/agile3d/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cw/anaconda3/envs/agile3d/lib/python3.10/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 171, in forward
    outfeat = self.pooling.apply(
  File "/home/cw/anaconda3/envs/agile3d/lib/python3.10/site-packages/MinkowskiEngine/MinkowskiPooling.py", line 70, in forward
    out_feat, num_nonzero = fw_fn(
RuntimeError: <unknown> at /tmp/pip-req-build-eavlxacw/src/gpu.cu:100
wandb: 🚀 View run dandy-armadillo-300 at: https://wandb.ai/congwei-shenyang-institute-of-automation/AGILE3D/runs/ccemxb5c
wandb: Find logs at: wandb/run-20241128_120602-ccemxb5c/logs

**Comment by ywyue** [comment]
Hi @congwei45, did you follow the https://github.com/ywyue/AGILE3D/blob/main/installation.md guide to install the Minkowski Engine?
